### PR TITLE
Added Shared dir into the deployment structure

### PR DESCRIPTION
**Pull request by renatomefi**
Shared dir was always missing, now it's here!

### CODE REVIEW

**Comment by renatomefi** [comment]
@eXistenZNL could you please check it? Thanks

**Comment by eXistenZNL** [comment]
@renatomefi please assign me as a reviewer next time and I will review :)

I thought that shared is not a thing in the deploy structure that was made up by Capistrano and adopted by many others including Deployer and Rocketeer, but it turns out that Enrise accidently introduced the 'data' folder in favor of the 'shared' folder.

We could simply remove the data folder here to make sure we are in line with the Capistrano deploy structure, projects that are currently deployed and make use of a data folder will keep on working because Salt will not start removing the already created data folders.

Any thoughts @syphernl?

**Review by eXistenZNL — COMMENTED** [review]
We should drop the /data folder too, see my other comment. What to do sarge?

**Comment by syphernl** [comment]
@eXistenZNL If it's not being used we can remove it (as in: from the states). However, there _may_ be require's (I know @bobbybouwmann and @nstapelbroek have some `extend:` magic going on on the projects we're using this on.

**Comment by nstapelbroek** [comment]
Dropping in because I got mentioned :raising_hand_man: 

@eXistenZNL Renato is unable to assign people due to limitations in permissions.
@syphernl afaik my extend states do not touch the data folder. I've used extends for serving a different web root if i remember correctly. 

Lets merge this next week, so we'll have some more time in case anything breaks :see_no_evil:

**Comment by eXistenZNL** [comment]
@renatomefi @nstapelbroek Is this still relevant?

https://twitter.com/jergason/status/828350555047202816

**Comment by nstapelbroek** [comment]
times are changing and I'm starting to think that your deployment solution should be responsible for creating their working directories. This is especially relevant since containers are uprising and we're migrating some old-school deployments towards deployer.org, which changed it's file structure (approach) in the last release.  

I'm not sure about your opinions, but i'd rather remove the entire deploy structure from salt :see_no_evil:

**Comment by eXistenZNL** [comment]
Closing for now, please reopen if needed.

**Pull request closed without merging**
